// <auto-generated />
using System;
using BackendCore.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendCore.Migrations
{
    [DbContext(typeof(HomeManagementDbContext))]
    partial class HomeManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildingNews", b =>
                {
                    b.Property<Guid>("BuildingsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BuildingsId", "NewsId");

                    b.HasIndex("NewsId");

                    b.ToTable("BuildingNews");
                });

            modelBuilder.Entity("Entities.Models.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BillStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BillStatusId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfa7b59f-ba4d-4ddc-bfe4-49884dd0bd80"),
                            BillStatusId = 1,
                            Description = "",
                            IsDeleted = false,
                            RoomId = new Guid("4f2504e0-4f89-41d3-8a0c-0305e82c3303")
                        });
                });

            modelBuilder.Entity("Entities.Models.BillDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentElectricityReading")
                        .HasColumnType("int");

                    b.Property<int>("CurrentWaterReading")
                        .HasColumnType("int");

                    b.Property<decimal>("ElectricityPricePerMonth")
                        .HasColumnType("money");

                    b.Property<int>("PreviousElectricityReading")
                        .HasColumnType("int");

                    b.Property<int>("PreviousWaterReading")
                        .HasColumnType("int");

                    b.Property<decimal>("RoomRentPrice")
                        .HasColumnType("money");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WaterPricePerMonth")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("BillId")
                        .IsUnique();

                    b.ToTable("BillDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd5aabe7-f87b-4d27-9896-91a1ef83a91e"),
                            BillId = new Guid("bfa7b59f-ba4d-4ddc-bfe4-49884dd0bd80"),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentElectricityReading = 1161,
                            CurrentWaterReading = 120,
                            ElectricityPricePerMonth = 3200m,
                            PreviousElectricityReading = 1030,
                            PreviousWaterReading = 100,
                            RoomRentPrice = 4000000m,
                            WaterPricePerMonth = 15000m
                        });
                });

            modelBuilder.Entity("Entities.Models.BillStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BillStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Not Paid"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Overdue"
                        });
                });

            modelBuilder.Entity("Entities.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("ElectricityPricePerMonth")
                        .HasColumnType("money");

                    b.Property<string>("HomeManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WaterPricePerMonth")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("HomeManagerId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            Address = "123 Đường Chính",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả mẫu cho tòa nhà.",
                            ElectricityPricePerMonth = 2675.0m,
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3301",
                            IsDeleted = false,
                            Name = "Chung cư An Nhiên",
                            WaterPricePerMonth = 21000.0m
                        },
                        new
                        {
                            Id = new Guid("2f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            Address = "456 Đường Phong",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mô tả khác cho tòa nhà.",
                            ElectricityPricePerMonth = 2500.0m,
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3301",
                            IsDeleted = false,
                            Name = "Chung cư mini Lạc Quân",
                            WaterPricePerMonth = 22000.0m
                        },
                        new
                        {
                            Id = new Guid("5f2504e0-4f89-41d3-9a0c-0305e82c3305"),
                            Address = "789 Đường Sồi",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mô tả khác cho tòa nhà.",
                            ElectricityPricePerMonth = 2700.0m,
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3302",
                            IsDeleted = false,
                            Name = "Tòa nhà 68",
                            WaterPricePerMonth = 15000.0m
                        },
                        new
                        {
                            Id = new Guid("9f2504e0-4f89-41d3-9a0c-0305e82c3309"),
                            Address = "1617 Đường Thông",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mô tả cho tòa nhà.",
                            ElectricityPricePerMonth = 3500.0m,
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3307",
                            IsDeleted = false,
                            Name = "Chung cư mini 102",
                            WaterPricePerMonth = 27000.0m
                        },
                        new
                        {
                            Id = new Guid("cf2504e0-4f89-41d3-9a0c-0305e82c3312"),
                            Address = "2223 Đường Vũ Bạch",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mô tả cho tòa nhà.",
                            ElectricityPricePerMonth = 3400.0m,
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3310",
                            IsDeleted = false,
                            Name = "Trọ Vũ Bạch",
                            WaterPricePerMonth = 20000.0m
                        },
                        new
                        {
                            Id = new Guid("ff2504e0-4f89-41d3-9a0c-0305e82c3312"),
                            Address = "2223 Stupid Street",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mô tả cho tòa nhà.",
                            ElectricityPricePerMonth = 3400.0m,
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3310",
                            IsDeleted = false,
                            Name = "ABC Apartment",
                            WaterPricePerMonth = 20000.0m
                        });
                });

            modelBuilder.Entity("Entities.Models.BuildingResident", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PortraitPictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("BuildingResident");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entities.Models.BuildingService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("BuildingServices", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("BuildingServicesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1690607-068b-47df-973d-7babb3efc1e8"),
                            BuildingId = new Guid("cf2504e0-4f89-41d3-9a0c-0305e82c3312"),
                            Name = "Laundry Fee",
                            PricePerMonth = 100000m
                        },
                        new
                        {
                            Id = new Guid("9b9d671f-7196-49d2-9fe7-d439aa2dac3a"),
                            BuildingId = new Guid("cf2504e0-4f89-41d3-9a0c-0305e82c3312"),
                            Name = "Parking Fee",
                            PricePerMonth = 50000m
                        },
                        new
                        {
                            Id = new Guid("f5610f03-3992-428c-8c45-d31309c72799"),
                            BuildingId = new Guid("cf2504e0-4f89-41d3-9a0c-0305e82c3312"),
                            Name = "Trash Fee",
                            PricePerMonth = 20000m
                        },
                        new
                        {
                            Id = new Guid("8f696d6a-034b-41af-949a-969f78935a22"),
                            BuildingId = new Guid("9f2504e0-4f89-41d3-9a0c-0305e82c3309"),
                            Name = "Elevator Fee",
                            PricePerMonth = 20000m
                        });
                });

            modelBuilder.Entity("Entities.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("money");

                    b.Property<DateTime>("ExpectedCheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HomeManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumberOfTenants")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RealCheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HomeManagerId");

                    b.HasIndex("RequestStatusId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TenantId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("08be2e31-4abb-446c-8b22-d25d140aa0d7"),
                            CheckInDate = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deposit = 3000000m,
                            ExpectedCheckOutDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3301",
                            IsDeleted = false,
                            Note = "",
                            NumberOfTenants = 3,
                            RoomId = new Guid("4f2504e0-4f89-41d3-8a0c-0305e82c3303"),
                            TenantId = "B4E6EA80-F066-44F4-AA55-30E0A0FE30AF"
                        },
                        new
                        {
                            Id = new Guid("40c3a2c4-dede-4722-be95-48a67c45f552"),
                            CheckInDate = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deposit = 3000000m,
                            ExpectedCheckOutDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3301",
                            IsDeleted = false,
                            Note = "",
                            NumberOfTenants = 2,
                            RoomId = new Guid("4f2504e0-4f89-41d3-7a0c-0305e82c3303"),
                            TenantId = "A1E1F042-AB4A-431E-8A8E-710E2ECEFFC3"
                        },
                        new
                        {
                            Id = new Guid("df9af346-6a2e-4930-ad39-5480c984eff9"),
                            CheckInDate = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deposit = 3000000m,
                            ExpectedCheckOutDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3301",
                            IsDeleted = false,
                            Note = "",
                            NumberOfTenants = 3,
                            RoomId = new Guid("cbf552c9-bbfb-4920-9f43-9782c33d88e8"),
                            TenantId = "4F9038F6-DCFD-40D4-96ED-601686DB6B11"
                        },
                        new
                        {
                            Id = new Guid("417a93ea-bc60-4c30-a4c1-d3b856889b08"),
                            CheckInDate = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deposit = 3000000m,
                            ExpectedCheckOutDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3302",
                            IsDeleted = false,
                            Note = "",
                            NumberOfTenants = 1,
                            RoomId = new Guid("db740cec-f865-455b-874e-aa8e3436115f"),
                            TenantId = "86F1E1D1-5AB7-48D3-8B14-97B0AD42018E"
                        });
                });

            modelBuilder.Entity("Entities.Models.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HomeManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HomeManagerId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68d0f123-4855-4004-bdf2-aeebae8f7bde"),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đến giờ đóng tiền nhà rồi, không đóng không cho ở. Có 10 phút kể từ thông báo này để đóng.",
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3301",
                            Title = "Đóng tiền điện nước tháng 12/2023"
                        },
                        new
                        {
                            Id = new Guid("2a9306b5-7c9d-4cda-82c7-94c7641de97e"),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đến giờ đóng tiền nhà rồi, không đóng không cho ở. Có 10 phút kể từ thông báo này để đóng.",
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3302",
                            Title = "Đóng tiền nhà tháng 1/2024"
                        },
                        new
                        {
                            Id = new Guid("0b447141-a4eb-4444-9d6a-d35ba9693995"),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đến giờ đóng tiền nhà rồi, không đóng không cho ở. Có 10 phút kể từ thông báo này để đóng.",
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3306",
                            Title = "Đóng tiền điện nước tháng 12/2023"
                        });
                });

            modelBuilder.Entity("Entities.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReaded")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RequestStatusId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RequestStatusId");

                    b.HasIndex("TenantId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74f47318-9d30-47f0-9d6b-623c60acd9e7"),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsReaded = true,
                            Message = "Đóng tiền nhà tháng 12/2023",
                            TenantId = "B4E6EA80-F066-44F4-AA55-30E0A0FE30AF"
                        },
                        new
                        {
                            Id = new Guid("acdf8315-a60b-469d-90eb-e450ebb1526c"),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsReaded = false,
                            Message = "Đóng tiền nhà tháng 12/2023",
                            TenantId = "F63C6963-7A41-4AB5-AD8E-4FEF8A8A843F"
                        },
                        new
                        {
                            Id = new Guid("8088bf14-7543-4d5f-bb03-891998318b87"),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsReaded = false,
                            Message = "Đóng tiền nhà tháng 12/2023",
                            TenantId = "257862CB-BFD1-4D55-AB50-10D186E3E8F4"
                        });
                });

            modelBuilder.Entity("Entities.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HomeManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RequestStatusId")
                        .HasColumnType("int");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HomeManagerId");

                    b.HasIndex("RequestStatusId");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9d7aac9-6978-4b71-b6ab-f56ac147f8b3"),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Không có nước",
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3301",
                            IsDeleted = false,
                            RequestStatusId = 1,
                            RequestTypeId = 2,
                            TenantId = "B4E6EA80-F066-44F4-AA55-30E0A0FE30AF"
                        },
                        new
                        {
                            Id = new Guid("ba9f1f1a-46ad-4ebd-a5e3-f26daae31812"),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thêm bình nóng lạnh",
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3306",
                            IsDeleted = false,
                            RequestStatusId = 2,
                            RequestTypeId = 4,
                            TenantId = "F63C6963-7A41-4AB5-AD8E-4FEF8A8A843F"
                        },
                        new
                        {
                            Id = new Guid("9d387606-2a10-4119-b5a5-16176626de19"),
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Có điều khiển điều hòa không?",
                            HomeManagerId = "3F2504E0-4F89-41D3-9A0C-0305E82C3306",
                            IsDeleted = false,
                            RequestStatusId = 3,
                            RequestTypeId = 1,
                            TenantId = "257862CB-BFD1-4D55-AB50-10D186E3E8F4"
                        });
                });

            modelBuilder.Entity("Entities.Models.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Sent"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Rejected"
                        });
                });

            modelBuilder.Entity("Entities.Models.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("RequestTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Question"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Complain"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Request"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Suggestion"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Others"
                        });
                });

            modelBuilder.Entity("Entities.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("RoomNo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-8a0c-0305e82c3303"),
                            BuildingId = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "101"
                        },
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-7a0c-0305e82c3303"),
                            BuildingId = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "102"
                        },
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-6a0c-0305e82c3303"),
                            BuildingId = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "103"
                        },
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-5a0c-0305e82c3303"),
                            BuildingId = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "104"
                        },
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-4a0c-0305e82c3303"),
                            BuildingId = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "105"
                        },
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-31d3-5a0c-0305e82c3303"),
                            BuildingId = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "106"
                        },
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-3a0c-0305e82c3303"),
                            BuildingId = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "107"
                        },
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-360c-0305e82c3303"),
                            BuildingId = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "108"
                        },
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-350c-0305e82c3303"),
                            BuildingId = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "109"
                        },
                        new
                        {
                            Id = new Guid("4f2504e0-4f89-41d3-351c-0305e82c3303"),
                            BuildingId = new Guid("4f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "110"
                        },
                        new
                        {
                            Id = new Guid("99524668-bf7b-43fc-a198-37a66478c8e5"),
                            BuildingId = new Guid("2f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "201"
                        },
                        new
                        {
                            Id = new Guid("8eb065ee-c50c-4a7e-ac97-6c795e6c02a2"),
                            BuildingId = new Guid("2f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "202"
                        },
                        new
                        {
                            Id = new Guid("af339181-931c-4f9a-aa6a-06646aa77a75"),
                            BuildingId = new Guid("2f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "203"
                        },
                        new
                        {
                            Id = new Guid("3b4b679b-9c20-4c1a-8407-0b7d7bff797e"),
                            BuildingId = new Guid("2f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "204"
                        },
                        new
                        {
                            Id = new Guid("31652927-66b2-4cf0-8c88-6b1a10563aeb"),
                            BuildingId = new Guid("2f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "205"
                        },
                        new
                        {
                            Id = new Guid("72f654f5-aeb6-410e-b5e9-51328acb04e6"),
                            BuildingId = new Guid("2f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "206"
                        },
                        new
                        {
                            Id = new Guid("62caa73a-47cb-4b48-aaca-4052c0fdfb2e"),
                            BuildingId = new Guid("2f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "207"
                        },
                        new
                        {
                            Id = new Guid("cbf552c9-bbfb-4920-9f43-9782c33d88e8"),
                            BuildingId = new Guid("2f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "208"
                        },
                        new
                        {
                            Id = new Guid("28894308-5db2-4c90-99ad-45f9379a989b"),
                            BuildingId = new Guid("2f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "209"
                        },
                        new
                        {
                            Id = new Guid("3f907bfa-cb32-4804-81f6-395b301f262e"),
                            BuildingId = new Guid("2f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "210"
                        },
                        new
                        {
                            Id = new Guid("c4939b2e-d7d9-41c9-83ea-e9557fd22f26"),
                            BuildingId = new Guid("5f2504e0-4f89-41d3-9a0c-0305e82c3305"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "210"
                        },
                        new
                        {
                            Id = new Guid("db740cec-f865-455b-874e-aa8e3436115f"),
                            BuildingId = new Guid("5f2504e0-4f89-41d3-9a0c-0305e82c3305"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "211"
                        },
                        new
                        {
                            Id = new Guid("82bc05ba-6175-4452-ab6c-f168c25d58e1"),
                            BuildingId = new Guid("5f2504e0-4f89-41d3-9a0c-0305e82c3305"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "212"
                        },
                        new
                        {
                            Id = new Guid("8f4700c0-bfdc-48b6-8bfa-bb0bf12f5c7d"),
                            BuildingId = new Guid("5f2504e0-4f89-41d3-9a0c-0305e82c3305"),
                            IsDeleted = false,
                            Price = 2000000.0m,
                            RoomNo = "213"
                        },
                        new
                        {
                            Id = new Guid("a61fee38-6669-4f35-aa9a-2589c09e28bf"),
                            BuildingId = new Guid("9f2504e0-4f89-41d3-9a0c-0305e82c3309"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "200"
                        },
                        new
                        {
                            Id = new Guid("c717d609-50ca-4427-89a0-555b7d75fb80"),
                            BuildingId = new Guid("9f2504e0-4f89-41d3-9a0c-0305e82c3309"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "201"
                        },
                        new
                        {
                            Id = new Guid("5dee6fd4-2989-4268-968a-bd8aaa7099db"),
                            BuildingId = new Guid("9f2504e0-4f89-41d3-9a0c-0305e82c3309"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "202"
                        },
                        new
                        {
                            Id = new Guid("0c55994e-91aa-4ab1-bbc2-b845aa2078fb"),
                            BuildingId = new Guid("9f2504e0-4f89-41d3-9a0c-0305e82c3309"),
                            IsDeleted = false,
                            Price = 4000000.0m,
                            RoomNo = "203"
                        },
                        new
                        {
                            Id = new Guid("be270fd3-7488-4bd2-ac23-c36c898ecf66"),
                            BuildingId = new Guid("cf2504e0-4f89-41d3-9a0c-0305e82c3312"),
                            IsDeleted = false,
                            Price = 5000000.0m,
                            RoomNo = "401A"
                        },
                        new
                        {
                            Id = new Guid("8d1b5b5e-3c68-4a3b-bece-0544c71590b2"),
                            BuildingId = new Guid("cf2504e0-4f89-41d3-9a0c-0305e82c3312"),
                            IsDeleted = false,
                            Price = 5000000.0m,
                            RoomNo = "402A"
                        },
                        new
                        {
                            Id = new Guid("4bc0fa1c-39cc-44c7-9e67-334706bef121"),
                            BuildingId = new Guid("cf2504e0-4f89-41d3-9a0c-0305e82c3312"),
                            IsDeleted = false,
                            Price = 5000000.0m,
                            RoomNo = "403A"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            ConcurrencyStamp = "f37016d3-5406-46bf-a45c-411b0580d72b",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-583d56fd7210",
                            ConcurrencyStamp = "25881f61-aad4-41c6-9407-d01d06d66e40",
                            Name = "Tenant",
                            NormalizedName = "TENANT"
                        },
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-683d56fd7210",
                            ConcurrencyStamp = "ddf50698-f1c7-466f-a504-407286fb514c",
                            Name = "Home Manager",
                            NormalizedName = "HOME MAANAGER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "B4E6EA80-F066-44F4-AA55-30E0A0FE30AF",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "F63C6963-7A41-4AB5-AD8E-4FEF8A8A843F",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "257862CB-BFD1-4D55-AB50-10D186E3E8F4",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "A1E1F042-AB4A-431E-8A8E-710E2ECEFFC3",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "4F9038F6-DCFD-40D4-96ED-601686DB6B11",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "D7FBD8C3-8D8A-4DBB-BE44-34B9D9C6D012",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "FF4D981F-E335-4928-9F2C-DB378E6AFC5B",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "86F1E1D1-5AB7-48D3-8B14-97B0AD42018E",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "3F2504E0-4F89-41D3-9A0C-0305E82C3301",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "3F2504E0-4F89-41D3-9A0C-0305E82C3302",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "3F2504E0-4F89-41D3-9A0C-0305E82C3306",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "3F2504E0-4F89-41D3-9A0C-0305E82C3307",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "3F2504E0-4F89-41D3-9A0C-0305E82C3309",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        },
                        new
                        {
                            UserId = "3F2504E0-4F89-41D3-9A0C-0305E82C3310",
                            RoleId = "2c5e174e-3b0e-446f-86af-583d56fd7210"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Models.HomeManager", b =>
                {
                    b.HasBaseType("Entities.Models.BuildingResident");

                    b.HasDiscriminator().HasValue("HomeManager");

                    b.HasData(
                        new
                        {
                            Id = "3F2504E0-4F89-41D3-9A0C-0305E82C3301",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fd7811be-7672-48b3-8656-ce4c51bcf07e",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anh_tuan@example.com",
                            EmailConfirmed = false,
                            FullName = "Anh Tuấn",
                            IsDeleted = false,
                            IsMale = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEDVLtMOoN4uc3IQad9ExkTk0ZqcXP+TFyC03PUTKaFH1WoEDubaWrOGOqCbmVCmxaQ==",
                            PhoneNumber = "0551234567",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "baceabba-a764-4389-9eb0-9cb72d6ef1b7",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3F2504E0-4F89-41D3-9A0C-0305E82C3302",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4e0e7b29-109c-4e5d-bd9d-cc75a6cf65dd",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bich_hang@example.com",
                            EmailConfirmed = false,
                            FullName = "Bích Hằng",
                            IsDeleted = false,
                            IsMale = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEKQqNFhV+nrX3yY6gZqJu2AufmIZetyo5xQR7PXxuOG+MYYYBleHyf6FOmLzC74KrA==",
                            PhoneNumber = "0659876543",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "cdd91ae5-41e9-4513-a2bb-40ed6ecd02b3",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3F2504E0-4F89-41D3-9A0C-0305E82C3306",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "edec3322-6293-47a2-b2a8-f06edee31120",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lam_truong@example.com",
                            EmailConfirmed = false,
                            FullName = "Lâm Trường",
                            IsDeleted = true,
                            IsMale = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEKOtXZ8Mb63aZJPRlh7T9dwRmHvZTg85jyBxmvVTcZS0+P7+9tOR5zjMEtnHBFy9Yw==",
                            PhoneNumber = "0852227890",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "b152e5a5-ace4-40d4-a935-bc3c55dbd7f9",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3F2504E0-4F89-41D3-9A0C-0305E82C3307",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5544df34-0a8b-4209-89e6-de681a37f762",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "linh_chau@example.com",
                            EmailConfirmed = false,
                            FullName = "Linh Châu",
                            IsDeleted = false,
                            IsMale = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEIdyJtBy5BWXR1CYKAXzXiiMm9taS0qrPL+FNXgqLlbdQievlme52aDb1EZ/lUvQew==",
                            PhoneNumber = "0955556789",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "9fda5038-c58d-4230-afed-56913ab5597c",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3F2504E0-4F89-41D3-9A0C-0305E82C3309",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1125cb2c-7b33-43f4-bc1a-574847f51e26",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quynh_nhu@example.com",
                            EmailConfirmed = false,
                            FullName = "Quỳnh Như",
                            IsDeleted = false,
                            IsMale = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEKq1oCKK5EPoX4RmTbH3W/LulICDajW1fpQaAvqBH5Vh4jFZWfjPNPt5zti5+f0HVg==",
                            PhoneNumber = "0955555678",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "af0f989e-c865-402e-b8b2-7b142f88594c",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3F2504E0-4F89-41D3-9A0C-0305E82C3310",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d7a517d-1342-4e59-92b3-321c03ce050b",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hoang_son@example.com",
                            EmailConfirmed = false,
                            FullName = "Hoàng Sơn",
                            IsDeleted = false,
                            IsMale = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEJVSwSIdLKkhY2pMwec7ycR6vdpDYfMSsN2GyPtaaICGX24jKehiXbBB3PYrB0YbEA==",
                            PhoneNumber = "0955559012",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "fd161e6e-0aa8-44b2-80f5-55cccc20b98e",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Entities.Models.Tenant", b =>
                {
                    b.HasBaseType("Entities.Models.BuildingResident");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("RoomId");

                    b.HasDiscriminator().HasValue("Tenant");

                    b.HasData(
                        new
                        {
                            Id = "B4E6EA80-F066-44F4-AA55-30E0A0FE30AF",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ec6a3f13-ba30-49e9-ac29-4b60ffa8114d",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email1@example.com",
                            EmailConfirmed = false,
                            FullName = "Nguyễn Thị Linh",
                            IsDeleted = false,
                            IsMale = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "LINH123",
                            PasswordHash = "AQAAAAEAACcQAAAAEIIntrcg/RDHm/BWH4LPIeellml+hW9XWI7JxW1HkIm7xFqyKzn7AUwcd99/Ltakyw==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "a63968f3-6029-4dbe-b03b-fd9f93fc5805",
                            TwoFactorEnabled = false,
                            UserName = "linh123",
                            Address = "",
                            Dob = new DateTime(1990, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("4f2504e0-4f89-41d3-8a0c-0305e82c3303")
                        },
                        new
                        {
                            Id = "F63C6963-7A41-4AB5-AD8E-4FEF8A8A843F",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20486d0b-4577-483a-a345-82b3baae75fb",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hyen4132@example.com",
                            EmailConfirmed = false,
                            FullName = "Hoàng Thị Yến",
                            IsDeleted = false,
                            IsMale = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "HYEN4132",
                            PasswordHash = "AQAAAAEAACcQAAAAEFnkTwAuaFH/2z2egf/x9ma/iRAddRJgAFtLYfEXIYUtgSmMT3f9Rqs33ltJINCnZw==",
                            PhoneNumber = "0976543210",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "927064f0-6a92-4501-9d0d-34a8c14c6315",
                            TwoFactorEnabled = false,
                            UserName = "hyen4132",
                            Address = "",
                            Dob = new DateTime(1991, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("4f2504e0-4f89-41d3-8a0c-0305e82c3303")
                        },
                        new
                        {
                            Id = "257862CB-BFD1-4D55-AB50-10D186E3E8F4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "92e4b7b3-1fe9-4887-b3a7-b62223ee3cd4",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yen123@example.com",
                            EmailConfirmed = false,
                            FullName = "Vũ Hoàng Yến",
                            IsDeleted = false,
                            IsMale = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "YEN123",
                            PasswordHash = "AQAAAAEAACcQAAAAED+7DMoqZ3Tu+aFhyat6eZUmS+NAsMutjh+64Zbf7bS/R+iNvCSCAScLO2jC9H3yXQ==",
                            PhoneNumber = "0965432109",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "42993da7-52ba-4ae8-a0e6-3bc1a5e13a2f",
                            TwoFactorEnabled = false,
                            UserName = "yen123",
                            Address = "",
                            Dob = new DateTime(1992, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("4f2504e0-4f89-41d3-8a0c-0305e82c3303")
                        },
                        new
                        {
                            Id = "A1E1F042-AB4A-431E-8A8E-710E2ECEFFC3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0e8ac560-4153-45c4-b470-1b40039055d1",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tva@example.com",
                            EmailConfirmed = false,
                            FullName = "Trần Văn A",
                            IsDeleted = false,
                            IsMale = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "TVA",
                            PasswordHash = "AQAAAAEAACcQAAAAEMHp5C/CSws/+4pI1WfXbkE1McYTensYF+ZqfOfO7fBatc2dln1Cr+3DxaVe1rO1Mw==",
                            PhoneNumber = "0954321098",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "3a2aae43-f906-4cc8-ba99-f75d35c7fd56",
                            TwoFactorEnabled = false,
                            UserName = "tva",
                            Address = "",
                            Dob = new DateTime(1985, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("4f2504e0-4f89-41d3-7a0c-0305e82c3303")
                        },
                        new
                        {
                            Id = "4F9038F6-DCFD-40D4-96ED-601686DB6B11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0fdb94e-6127-4d6e-90b5-046525cdad96",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ptb@example.com",
                            EmailConfirmed = false,
                            FullName = "Phạm Thị B",
                            IsDeleted = false,
                            IsMale = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "PTB",
                            PasswordHash = "AQAAAAEAACcQAAAAEEpiIYCtrEdZMIwu+H/gxN5qgHLMn+9ZcqioZWfCkxKn6rTRmmzdjWULf4y7I2CxcA==",
                            PhoneNumber = "0943210987",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "5cf9cbb7-4406-4560-873e-8fece1fdaf67",
                            TwoFactorEnabled = false,
                            UserName = "ptb",
                            Address = "",
                            Dob = new DateTime(1986, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("cbf552c9-bbfb-4920-9f43-9782c33d88e8")
                        },
                        new
                        {
                            Id = "D7FBD8C3-8D8A-4DBB-BE44-34B9D9C6D012",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6e5b640-7eab-4b3e-a6e2-b9f2b5781b4b",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lvc@example.com",
                            EmailConfirmed = false,
                            FullName = "Phạm Thị C",
                            IsDeleted = false,
                            IsMale = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "LVC",
                            PasswordHash = "AQAAAAEAACcQAAAAEKXD40Cs4Ccf/AoH6/govGx35wCV1eN98o0VM09pKW3eHvhac8o+qq/yjGGdkYOViw==",
                            PhoneNumber = "0932109876",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "f511c9e8-97ac-4037-97d8-6e4c27127e6b",
                            TwoFactorEnabled = false,
                            UserName = "lvc",
                            Address = "",
                            Dob = new DateTime(1987, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("cbf552c9-bbfb-4920-9f43-9782c33d88e8")
                        },
                        new
                        {
                            Id = "FF4D981F-E335-4928-9F2C-DB378E6AFC5B",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c3cecdcf-ac9e-406a-bb4f-fb4826279dc9",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ntd@example.com",
                            EmailConfirmed = false,
                            FullName = "Nguyễn Thị D",
                            IsDeleted = false,
                            IsMale = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "NTD",
                            PasswordHash = "AQAAAAEAACcQAAAAED9DpQqJ9X7d2oUkWVRPvQG56F+kfZLnPJ9Om//GxKET9fD6x4DZxOfZ+RH6grgTsg==",
                            PhoneNumber = "0921098765",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "e60c99c2-be33-4260-848e-4edf74f809eb",
                            TwoFactorEnabled = false,
                            UserName = "ntd",
                            Address = "",
                            Dob = new DateTime(1988, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("cbf552c9-bbfb-4920-9f43-9782c33d88e8")
                        },
                        new
                        {
                            Id = "86F1E1D1-5AB7-48D3-8B14-97B0AD42018E",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dcc1789a-fdeb-4f80-b325-42dcb9c55ca0",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tte@example.com",
                            EmailConfirmed = false,
                            FullName = "Trần Thị E",
                            IsDeleted = false,
                            IsMale = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "TTE",
                            PasswordHash = "AQAAAAEAACcQAAAAEIwofQVg7J0ATs7LKSNtD5uxfUzkyFRyRhJj7yuomVgiPNpkd3zsLeyVkPp3e0bakQ==",
                            PhoneNumber = "0910987654",
                            PhoneNumberConfirmed = false,
                            PortraitPictureUrl = "",
                            SecurityStamp = "c7231b2f-bb23-4921-94f4-072a193e8b36",
                            TwoFactorEnabled = false,
                            UserName = "tte",
                            Address = "",
                            Dob = new DateTime(1989, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = new Guid("db740cec-f865-455b-874e-aa8e3436115f")
                        });
                });

            modelBuilder.Entity("BuildingNews", b =>
                {
                    b.HasOne("Entities.Models.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.News", null)
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Bill", b =>
                {
                    b.HasOne("Entities.Models.BillStatus", "BillStatus")
                        .WithMany("Bills")
                        .HasForeignKey("BillStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.Room", "Room")
                        .WithMany("Bills")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BillStatus");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Entities.Models.BillDetail", b =>
                {
                    b.HasOne("Entities.Models.Bill", "Bill")
                        .WithOne("BillDetail")
                        .HasForeignKey("Entities.Models.BillDetail", "BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Entities.Models.Building", b =>
                {
                    b.HasOne("Entities.Models.HomeManager", "HomeManager")
                        .WithMany("Buildings")
                        .HasForeignKey("HomeManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HomeManager");
                });

            modelBuilder.Entity("Entities.Models.BuildingService", b =>
                {
                    b.HasOne("Entities.Models.Building", "Building")
                        .WithMany("BuildingServices")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Entities.Models.Contract", b =>
                {
                    b.HasOne("Entities.Models.HomeManager", "HomeManager")
                        .WithMany()
                        .HasForeignKey("HomeManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.RequestStatus", null)
                        .WithMany("Contracts")
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Entities.Models.Room", "Room")
                        .WithMany("Contracts")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany("Contracts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HomeManager");

                    b.Navigation("Room");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.News", b =>
                {
                    b.HasOne("Entities.Models.HomeManager", "HomeManager")
                        .WithMany("News")
                        .HasForeignKey("HomeManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HomeManager");
                });

            modelBuilder.Entity("Entities.Models.Notification", b =>
                {
                    b.HasOne("Entities.Models.RequestStatus", null)
                        .WithMany("Notifications")
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany("Notifications")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.Request", b =>
                {
                    b.HasOne("Entities.Models.HomeManager", "HomeManager")
                        .WithMany("Requests")
                        .HasForeignKey("HomeManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.RequestStatus", "RequestStatus")
                        .WithMany("Requests")
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.RequestType", "RequestType")
                        .WithMany("Requests")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany("Requests")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HomeManager");

                    b.Navigation("RequestStatus");

                    b.Navigation("RequestType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.Room", b =>
                {
                    b.HasOne("Entities.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.BuildingResident", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.BuildingResident", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.BuildingResident", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.BuildingResident", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Tenant", b =>
                {
                    b.HasOne("Entities.Models.Room", "Room")
                        .WithMany("Tenants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Entities.Models.Bill", b =>
                {
                    b.Navigation("BillDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.BillStatus", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("Entities.Models.Building", b =>
                {
                    b.Navigation("BuildingServices");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Entities.Models.RequestStatus", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Notifications");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Entities.Models.RequestType", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Entities.Models.Room", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Contracts");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Entities.Models.HomeManager", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("News");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Entities.Models.Tenant", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Notifications");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
